### ISSUE TITLE
notification wont  show on android 8

### ISSUE THREAD

**Issue by brwa88** [derek82511/cordova-azure-notification-hubs#2]
i have made an app using IONIC V1 and this plugin 
i receive notifications on android 7 and below but nothing is shown when i send notifications to android 8 and above any advice

**Comment by derek82511** [comment]
Hi brwa,
I updated the plugin version to 1.0.6 for android 8+ notification issue using API 26+ .
[https://github.com/derek82511/cordova-azure-notification-hubs/commit/afe8ba3460a56c36bfe11d6970b5299f055fb369](url)
