### ISSUE TITLE
customize notification sound

### ISSUE THREAD

**Issue by brwa88** [derek82511/cordova-azure-notification-hubs#7]
is there a way to customize notification sound with this plugin?

**Comment by derek82511** [comment]
You can put your custom sound inside the fcm data payload and apns payload.

[Android sound implementation](https://github.com/derek82511/cordova-azure-notification-hubs/blob/ff61a510056afd4e3a120968502491bf5786193a/src/android/com/adobe/phonegap/push/FCMService.java#L701-L720)
[APNS payload](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html)
